/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dhpm11.tuan3;

/**
 *
 * @author Admin
 */
public class Calculator extends javax.swing.JFrame {
    private long a= 0;
    private String phepToan = "";
    /**
     * Creates new form NewJFrame
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnTren = new javax.swing.JPanel();
        txtHienThi = new java.awt.TextField();
        pnDuoi = new javax.swing.JPanel();
        btnSo1 = new javax.swing.JButton();
        btnSo2 = new javax.swing.JButton();
        btnSo3 = new javax.swing.JButton();
        btnChia = new javax.swing.JButton();
        btnSQRT = new javax.swing.JButton();
        btnSo4 = new javax.swing.JButton();
        btnSo5 = new javax.swing.JButton();
        btnSo6 = new javax.swing.JButton();
        btnNhan = new javax.swing.JButton();
        btnPhanTram = new javax.swing.JButton();
        btnSo7 = new javax.swing.JButton();
        btnSo8 = new javax.swing.JButton();
        btnSo9 = new javax.swing.JButton();
        btnTru = new javax.swing.JButton();
        btnMotPhanX = new javax.swing.JButton();
        btnSo0 = new javax.swing.JButton();
        btnCongChiaTru = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnCong = new javax.swing.JButton();
        btnBang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        txtHienThi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtHienThi.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtHienThi.setText("0");
        txtHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHienThiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTrenLayout = new javax.swing.GroupLayout(pnTren);
        pnTren.setLayout(pnTrenLayout);
        pnTrenLayout.setHorizontalGroup(
            pnTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTrenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHienThi, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTrenLayout.setVerticalGroup(
            pnTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTrenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnTren, java.awt.BorderLayout.PAGE_START);

        pnDuoi.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        pnDuoi.setLayout(new java.awt.GridLayout(4, 5));

        btnSo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSo1.setText("1");
        btnSo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo1ActionPerformed(evt);
            }
        });
        pnDuoi.add(btnSo1);

        btnSo2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSo2.setText("2");
        btnSo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo2ActionPerformed(evt);
            }
        });
        pnDuoi.add(btnSo2);

        btnSo3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSo3.setText("3");
        btnSo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo3ActionPerformed(evt);
            }
        });
        pnDuoi.add(btnSo3);

        btnChia.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnChia.setText("/");
        btnChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiaActionPerformed(evt);
            }
        });
        pnDuoi.add(btnChia);

        btnSQRT.setText("sqrt");
        pnDuoi.add(btnSQRT);

        btnSo4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSo4.setText("4");
        btnSo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo4ActionPerformed(evt);
            }
        });
        pnDuoi.add(btnSo4);

        btnSo5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSo5.setText("5");
        btnSo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo5ActionPerformed(evt);
            }
        });
        pnDuoi.add(btnSo5);

        btnSo6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSo6.setText("6");
        btnSo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo6ActionPerformed(evt);
            }
        });
        pnDuoi.add(btnSo6);

        btnNhan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNhan.setText("*");
        btnNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanActionPerformed(evt);
            }
        });
        pnDuoi.add(btnNhan);

        btnPhanTram.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPhanTram.setText("%");
        pnDuoi.add(btnPhanTram);

        btnSo7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSo7.setText("7");
        btnSo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo7ActionPerformed(evt);
            }
        });
        pnDuoi.add(btnSo7);

        btnSo8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSo8.setText("8");
        btnSo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo8ActionPerformed(evt);
            }
        });
        pnDuoi.add(btnSo8);

        btnSo9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSo9.setText("9");
        btnSo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo9ActionPerformed(evt);
            }
        });
        pnDuoi.add(btnSo9);

        btnTru.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnTru.setText("-");
        btnTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruActionPerformed(evt);
            }
        });
        pnDuoi.add(btnTru);

        btnMotPhanX.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMotPhanX.setText("1/x");
        pnDuoi.add(btnMotPhanX);

        btnSo0.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSo0.setText("0");
        btnSo0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSo0ActionPerformed(evt);
            }
        });
        pnDuoi.add(btnSo0);

        btnCongChiaTru.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCongChiaTru.setText("+/-");
        pnDuoi.add(btnCongChiaTru);

        btnC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnC.setText("c");
        pnDuoi.add(btnC);

        btnCong.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCong.setText("+");
        btnCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongActionPerformed(evt);
            }
        });
        pnDuoi.add(btnCong);

        btnBang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBang.setText("=");
        btnBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBangActionPerformed(evt);
            }
        });
        pnDuoi.add(btnBang);

        jPanel1.add(pnDuoi, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo1ActionPerformed
        String gt= this.txtHienThi.getText();
        if(gt.length()< 12 ){
            if (gt.equals(0)) gt = "";
            
            long so  = Long.parseLong(gt + btnSo1.getText());
            
            this.txtHienThi.setText(String.valueOf(so));
        }
            
    }//GEN-LAST:event_btnSo1ActionPerformed

    private void btnSo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo2ActionPerformed
          String gt= this.txtHienThi.getText();
        if(gt.length()< 12 ){
            if (gt.equals(0)) gt = "";
            
            long so  = Long.parseLong(gt + btnSo2.getText());
            
            this.txtHienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnSo2ActionPerformed

    private void btnSo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo3ActionPerformed
          String gt= this.txtHienThi.getText();
        if(gt.length()< 12 ){
            if (gt.equals(0)) gt = "";
            
            long so  = Long.parseLong(gt + btnSo3.getText());
            
            this.txtHienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnSo3ActionPerformed

    private void btnSo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo4ActionPerformed
          String gt= this.txtHienThi.getText();
        if(gt.length()< 12 ){
            if (gt.equals(0)) gt = "";
            
            long so  = Long.parseLong(gt + btnSo4.getText());
            
            this.txtHienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnSo4ActionPerformed

    private void btnSo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo5ActionPerformed
          String gt= this.txtHienThi.getText();
        if(gt.length()< 12 ){
            if (gt.equals(0)) gt = "";
            
            long so  = Long.parseLong(gt + btnSo5.getText());
            
            this.txtHienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnSo5ActionPerformed

    private void btnSo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo6ActionPerformed
          String gt= this.txtHienThi.getText();
        if(gt.length()< 12 ){
            if (gt.equals(0)) gt = "";
            
            long so  = Long.parseLong(gt + btnSo6.getText());
            
            this.txtHienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnSo6ActionPerformed

    private void btnSo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo7ActionPerformed
          String gt= this.txtHienThi.getText();
        if(gt.length()< 12 ){
            if (gt.equals(0)) gt = "";
            
            long so  = Long.parseLong(gt + btnSo7.getText());
            
            this.txtHienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnSo7ActionPerformed

    private void btnSo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo8ActionPerformed
          String gt= this.txtHienThi.getText();
        if(gt.length()< 12 ){
            if (gt.equals(0)) gt = "";
            
            long so  = Long.parseLong(gt + btnSo8.getText());
            
            this.txtHienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnSo8ActionPerformed

    private void btnSo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo9ActionPerformed
          String gt= this.txtHienThi.getText();
        if(gt.length()< 12 ){
            if (gt.equals(0)) gt = "";
            
            long so  = Long.parseLong(gt + btnSo9.getText());
            
            this.txtHienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnSo9ActionPerformed

    private void btnSo0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSo0ActionPerformed
          String gt= this.txtHienThi.getText();
        if(gt.length()< 12 ){
            if (gt.equals(0)) gt = "";
            
            long so  = Long.parseLong(gt + btnSo0.getText());
            
            this.txtHienThi.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btnSo0ActionPerformed

    private void txtHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHienThiActionPerformed

    }//GEN-LAST:event_txtHienThiActionPerformed

    private void btnChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiaActionPerformed
        this.a = Long.parseLong(this.txtHienThi.getText());
        if(this.a != 0)
        {
            this.phepToan = "/";
            this.txtHienThi.setText("0");
        }
    }//GEN-LAST:event_btnChiaActionPerformed

    private void btnNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanActionPerformed
        this.a = Long.parseLong(this.txtHienThi.getText());
        this.phepToan = "*";
        this.txtHienThi.setText("0");
    }//GEN-LAST:event_btnNhanActionPerformed

    private void btnTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruActionPerformed
        this.a = Long.parseLong(this.txtHienThi.getText());
        this.phepToan = "-";
        this.txtHienThi.setText("0");
    }//GEN-LAST:event_btnTruActionPerformed

    private void btnCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongActionPerformed
        this.a = Long.parseLong(this.txtHienThi.getText());
        this.phepToan = "+";
        this.txtHienThi.setText("0");
    }//GEN-LAST:event_btnCongActionPerformed

    private void btnBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBangActionPerformed
        if(this.phepToan.length() > 0)
        {
            long b = Long.parseLong(this.txtHienThi.getText());
            if(this.phepToan.equals("+"))
            {
                long kq = this.a + b;
                this.txtHienThi.setText(String.valueOf(kq));
            }
            if(this.phepToan.equals("-"))
            {
                long kq = this.a - b;
                this.txtHienThi.setText(String.valueOf(kq));
            }
            if(this.phepToan.equals("*"))
            {
                long kq = this.a * b;
                this.txtHienThi.setText(String.valueOf(kq));
            }
              if(this.phepToan.equals("/"))
            {
                long kq = this.a / b;
                this.txtHienThi.setText(String.valueOf(kq));
            }
              this.phepToan = "";
              this.a = 0;
        }
    }//GEN-LAST:event_btnBangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBang;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnChia;
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnCongChiaTru;
    private javax.swing.JButton btnMotPhanX;
    private javax.swing.JButton btnNhan;
    private javax.swing.JButton btnPhanTram;
    private javax.swing.JButton btnSQRT;
    private javax.swing.JButton btnSo0;
    private javax.swing.JButton btnSo1;
    private javax.swing.JButton btnSo2;
    private javax.swing.JButton btnSo3;
    private javax.swing.JButton btnSo4;
    private javax.swing.JButton btnSo5;
    private javax.swing.JButton btnSo6;
    private javax.swing.JButton btnSo7;
    private javax.swing.JButton btnSo8;
    private javax.swing.JButton btnSo9;
    private javax.swing.JButton btnTru;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnDuoi;
    private javax.swing.JPanel pnTren;
    private java.awt.TextField txtHienThi;
    // End of variables declaration//GEN-END:variables
}
