/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dhpm11.tuan4;
import com.dhpm11.tuan4.Suppliers;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class BooksSuppliers extends javax.swing.JFrame {
    private ArrayList<Suppliers> list;
    DefaultTableModel model;
    /**
     * Creates new form BooksSuppliers
     */
    public BooksSuppliers() {
        initComponents();
        this.setLocationRelativeTo(null);
        list = new DAO().getListSuppliers();
        model = (DefaultTableModel) tblThongTin.getModel();
        showTable();
    }
    
    public  void showTable(){
        for (Suppliers s : list){
            model.addRow(new Object[]{
                 s.getID(), s.getName(), s.getType(), s.getAddress(), s.getContact(), s.getEmail(), s.getRemarks()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTong = new javax.swing.JPanel();
        pnBooksSuppliers = new javax.swing.JPanel();
        txtBooksSuppliers = new javax.swing.JLabel();
        pnTextField = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblContactNow = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblRemarks = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtContectNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        ckbBooks = new javax.swing.JCheckBox();
        ckbNewPapers = new javax.swing.JCheckBox();
        ckbJournalsandMagazines = new javax.swing.JCheckBox();
        txtRemarks = new java.awt.TextArea();
        pnButton = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        pnTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongTin = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnBooksSuppliers.setBackground(new java.awt.Color(0, 102, 102));

        txtBooksSuppliers.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtBooksSuppliers.setForeground(new java.awt.Color(255, 255, 255));
        txtBooksSuppliers.setText("BOOKS SUPPLIERS");

        javax.swing.GroupLayout pnBooksSuppliersLayout = new javax.swing.GroupLayout(pnBooksSuppliers);
        pnBooksSuppliers.setLayout(pnBooksSuppliersLayout);
        pnBooksSuppliersLayout.setHorizontalGroup(
            pnBooksSuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBooksSuppliersLayout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(txtBooksSuppliers)
                .addGap(250, 250, 250))
        );
        pnBooksSuppliersLayout.setVerticalGroup(
            pnBooksSuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBooksSuppliersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBooksSuppliers, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblID.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblID.setText("Suppliers ID");

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblName.setText("Suppliers Name");

        lblType.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblType.setText("Suppliers Type");

        lblAddress.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblAddress.setText("Address");

        lblContactNow.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblContactNow.setText("Contact Now");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmail.setText("Email ID");

        lblRemarks.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblRemarks.setText("Remarks");

        txtID.setEnabled(false);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        ckbBooks.setText("Books");
        ckbBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbBooksActionPerformed(evt);
            }
        });

        ckbNewPapers.setText("New Papers");

        ckbJournalsandMagazines.setText("Journals and Magazines");

        javax.swing.GroupLayout pnTextFieldLayout = new javax.swing.GroupLayout(pnTextField);
        pnTextField.setLayout(pnTextFieldLayout);
        pnTextFieldLayout.setHorizontalGroup(
            pnTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTextFieldLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTextFieldLayout.createSequentialGroup()
                        .addGroup(pnTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTextFieldLayout.createSequentialGroup()
                                .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addGap(239, 239, 239))
                            .addGroup(pnTextFieldLayout.createSequentialGroup()
                                .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(224, 224, 224)))
                        .addComponent(ckbNewPapers, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(291, 291, 291))
                    .addGroup(pnTextFieldLayout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                            .addComponent(txtName))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnTextFieldLayout.createSequentialGroup()
                        .addGroup(pnTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblContactNow, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRemarks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(pnTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnTextFieldLayout.createSequentialGroup()
                                .addComponent(ckbBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                                .addComponent(ckbJournalsandMagazines, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtContectNo)
                            .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                            .addComponent(txtRemarks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnTextFieldLayout.setVerticalGroup(
            pnTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTextFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(ckbBooks)
                    .addComponent(ckbNewPapers)
                    .addComponent(ckbJournalsandMagazines))
                .addGap(18, 18, 18)
                .addGroup(pnTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactNow)
                    .addComponent(txtContectNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTextFieldLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTextFieldLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pnButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSave.setBackground(new java.awt.Color(255, 0, 0));
        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(153, 0, 153));
        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnNew.setBackground(new java.awt.Color(0, 0, 255));
        btnNew.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 0));
        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnButtonLayout = new javax.swing.GroupLayout(pnButton);
        pnButton.setLayout(pnButtonLayout);
        pnButtonLayout.setHorizontalGroup(
            pnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        pnButtonLayout.setVerticalGroup(
            pnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblThongTin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblThongTin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Suppliers ID", "Suppliers Name", "Suppliers Type", "Address", "Contect No", "Email ID", "Remarks"
            }
        ));
        tblThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThongTin);

        javax.swing.GroupLayout pnTableLayout = new javax.swing.GroupLayout(pnTable);
        pnTable.setLayout(pnTableLayout);
        pnTableLayout.setHorizontalGroup(
            pnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnTableLayout.setVerticalGroup(
            pnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnTongLayout = new javax.swing.GroupLayout(pnTong);
        pnTong.setLayout(pnTongLayout);
        pnTongLayout.setHorizontalGroup(
            pnTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnTongLayout.createSequentialGroup()
                .addComponent(pnBooksSuppliers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        pnTongLayout.setVerticalGroup(
            pnTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTongLayout.createSequentialGroup()
                .addComponent(pnBooksSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void ckbBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbBooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbBooksActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Suppliers s = new Suppliers();
        s.setID(txtID.getText());
        if(new DAO().DeleteData(s)){
            JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Lỗi! xóa không thành công");
        }
        showResult();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtID.setText("");
        txtAddress.setText("");
        txtContectNo.setText("");
        txtEmail.setText("");
        txtName.setText("");
        txtRemarks.setText("");
        ckbBooks.setSelected(false);
        ckbJournalsandMagazines.setSelected(false);
        ckbNewPapers.setSelected(false);
        
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Suppliers s= new Suppliers();
        s.setName(txtName.getText());
        s.setAddress(txtAddress.getText());
        s.setContact(txtContectNo.getText());
        s.setEmail(txtEmail.getText());
        s.setRemarks(txtRemarks.getText());
        String tam = "";
        if(ckbBooks.isSelected())
        {
            tam = tam + "Books ";
        }
        if(ckbNewPapers.isSelected())
        {
            tam = tam + "New Papers ";
        }
        if(ckbJournalsandMagazines.isSelected())
        {
            tam = tam + "Journalsand Magazines";
        }
        s.setType(tam);
        if (new DAO().addSuppliers(s))
        {
            JOptionPane.showMessageDialog(rootPane, "Lưu thành công");
            list.add(s);
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Không lưu được");
        }
        showResult();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinMouseClicked
        LoadData();
    }//GEN-LAST:event_tblThongTinMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        Suppliers s = new Suppliers();
        s.setID(txtID.getText());
        s.setName(txtName.getText());
        s.setAddress(txtAddress.getText());
        s.setContact(txtContectNo.getText());
        s.setEmail(txtEmail.getText());
        s.setRemarks(txtRemarks.getText());
        String tam = "";
        if(ckbBooks.isSelected())
        {
            tam = tam + "Books ";
        }
        if(ckbNewPapers.isSelected())
        {
            tam = tam + "New Papers ";
        }
        if(ckbJournalsandMagazines.isSelected())
        {
            tam = tam + "Journalsand Magazines";
        }
        s.setType(tam);
        if (new DAO().UpDateData(s))
        {
            JOptionPane.showMessageDialog(rootPane, "Thay Đổi thành công");
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Lỗi!");
        }
        showResult();
    }//GEN-LAST:event_btnUpdateActionPerformed

    public  void LoadData(){
        tblThongTin.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
        if(tblThongTin.getSelectedRow() >=0){
            txtID.setText(tblThongTin.getValueAt(tblThongTin.getSelectedRow(),0) +"");
            txtName.setText(tblThongTin.getValueAt(tblThongTin.getSelectedRow(),1) +"");
            txtAddress.setText(tblThongTin.getValueAt(tblThongTin.getSelectedRow(),3) +"");
            txtContectNo.setText(tblThongTin.getValueAt(tblThongTin.getSelectedRow(),4) +"");
            txtEmail.setText(tblThongTin.getValueAt(tblThongTin.getSelectedRow(),5) +"");
            txtRemarks.setText(tblThongTin.getValueAt(tblThongTin.getSelectedRow(),6) +"");
                }        
             }
        });
        
        
        
        
        
    /*    int i = tblThongTin.getSelectedRow();
        txtID.setText((String)(model.getValueAt(i, 0)));
        txtName.setText((String)(model.getValueAt(i, 1)));
        txtContectNo.setText((String)(model.getValueAt(i, 2)));
        txtEmail.setText((String)(model.getValueAt(i, 3)));
        txtRemarks.setText((String)(model.getValueAt(i, 4)));
      */  
    }
    
    public void showResult(){
        Suppliers s = list.get(list.size() - 1);
         model.addRow(new Object[]{
                 s.getID(), s.getName(), s.getType(), s.getAddress(), s.getContact(), s.getEmail(), s.getRemarks()
            });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BooksSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BooksSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BooksSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BooksSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BooksSuppliers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox ckbBooks;
    private javax.swing.JCheckBox ckbJournalsandMagazines;
    private javax.swing.JCheckBox ckbNewPapers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblContactNow;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRemarks;
    private javax.swing.JLabel lblType;
    private javax.swing.JPanel pnBooksSuppliers;
    private javax.swing.JPanel pnButton;
    private javax.swing.JPanel pnTable;
    private javax.swing.JPanel pnTextField;
    private javax.swing.JPanel pnTong;
    private javax.swing.JTable tblThongTin;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JLabel txtBooksSuppliers;
    private javax.swing.JTextField txtContectNo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private java.awt.TextArea txtRemarks;
    // End of variables declaration//GEN-END:variables
}
